user:
  name: Guritso
  bio: Anime fan sharing my latest watches and open-source projects.  
  avatar: https://avatares-nine.vercel.app/api/avatar
  myAnimeList: guritso
  github: guritso

social:
  - name: Buy me a coffee
    url: https://buymeacoffee.com/guritso
    icon: fa-solid fa-mug-hot

  - name: X
    url: https://x.com/guritso
    icon: fa-brands fa-x-twitter

  - name: GitHub
    url: https://github.com/Guritso
    icon: fa-brands fa-github

  - name: MyAnimeList
    url: https://myanimelist.net/profile/Guritso

anime:
  filter:
    - watching
    - completed
  limit: 20
  rowSpeed: 0.6

repos:
  exclude:
    - guritso
  forks: false
  archiveds: false
  limit: 10

theme: dark
vhs: true