user:
  name: Guritso
  bio: Hello, I like to code and watch animes, so here is some of my projects and latest animes I've watched.
  avatar: https://s.gravatar.com/avatar/a2087d7427bd15a4986b8a02f12d2590c87e7f6fcf22de02489c305f98217b43?s=150
  myAnimeList: guritso
  github: guritso

social:
  - name: X
    url: https://x.com/guritso
    icon: fa-brands fa-x-twitter

  - name: GitHub
    url: https://github.com/Guritso
    icon: fa-brands fa-github

  - name: MyAnimeList
    url: https://myanimelist.net/profile/Guritso

anime:
  filter:
    - watching
    - completed
  limit: 20
  rowSpeed: 0.6

repos:
  exclude:
    - guritso
    - gurizenit-site
  forks: false
  archiveds: false
  limit: 10

theme: dark
